// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvFXde2TW3AKhAYQMSnS3p_pBCdXS6MSI',
    appId: '1:110994836395:web:68af63b9dedb7fe54360ee',
    messagingSenderId: '110994836395',
    projectId: 'dstorres-29bbe',
    authDomain: 'dstorres-29bbe.firebaseapp.com',
    databaseURL: 'https://dstorres-29bbe-default-rtdb.firebaseio.com',
    storageBucket: 'dstorres-29bbe.appspot.com',
    measurementId: 'G-NTBG5QMP9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ1Z484lbCvx7sbIvUhFpT3En8ISUHSw4',
    appId: '1:110994836395:android:21401d83c9b033914360ee',
    messagingSenderId: '110994836395',
    projectId: 'dstorres-29bbe',
    databaseURL: 'https://dstorres-29bbe-default-rtdb.firebaseio.com',
    storageBucket: 'dstorres-29bbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTsxGYAxKycAxuQ11ey5Yc3r4DSHUR2UQ',
    appId: '1:110994836395:ios:db121c88a2fc886b4360ee',
    messagingSenderId: '110994836395',
    projectId: 'dstorres-29bbe',
    databaseURL: 'https://dstorres-29bbe-default-rtdb.firebaseio.com',
    storageBucket: 'dstorres-29bbe.appspot.com',
    iosClientId: '110994836395-72rsjcpahgiciu76ff0a6cllh6u4s72o.apps.googleusercontent.com',
    iosBundleId: 'com.example.plataformadstorres',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTsxGYAxKycAxuQ11ey5Yc3r4DSHUR2UQ',
    appId: '1:110994836395:ios:db121c88a2fc886b4360ee',
    messagingSenderId: '110994836395',
    projectId: 'dstorres-29bbe',
    databaseURL: 'https://dstorres-29bbe-default-rtdb.firebaseio.com',
    storageBucket: 'dstorres-29bbe.appspot.com',
    iosClientId: '110994836395-72rsjcpahgiciu76ff0a6cllh6u4s72o.apps.googleusercontent.com',
    iosBundleId: 'com.example.plataformadstorres',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvFXde2TW3AKhAYQMSnS3p_pBCdXS6MSI',
    appId: '1:110994836395:web:fe66373345c74eb74360ee',
    messagingSenderId: '110994836395',
    projectId: 'dstorres-29bbe',
    authDomain: 'dstorres-29bbe.firebaseapp.com',
    databaseURL: 'https://dstorres-29bbe-default-rtdb.firebaseio.com',
    storageBucket: 'dstorres-29bbe.appspot.com',
    measurementId: 'G-N83SYZWBWS',
  );

}